
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This script was run:

```{r, echo = F}
date()
print(params$seed)
nedre <- ((100 - params$intervall)/2)/100
ovre <- 1 - nedre

```


```{r,include = F, comment= FALSE, message= FALSE}
library(ggplot2)
library(betareg)

analyseSti <- "F:/Forskningsprosjekter/PDB 2794 - Immune responses aga_/Forskningsfiler/JOBO/CyTOF/Analyse i R OUS/"
 meta <- readxl::read_xlsx(fs::path(analyseSti, "STATAfil OUS pasienter FINAL 270121.xlsx"))
 kontrol <- readxl::read_xlsx(fs::path(analyseSti, "oversikt_kontroller030221.xlsx"))
 kontrol$Sex <- kontrol$`kjønn (kvinne=1, mann = 2)`
 kontrol$kont <- kontrol$Løpenummer...1
```


```{r, echo = F}
prepare_data <- function(){
    klu_temp <- read.csv2(fs::path(params$utSti, paste0("antallPerClusterOgPat_k_", ant_klu_i , "_seed", params$seed, params$selcected_name,  ".csv")))
  
  rownames(klu_temp) <- klu_temp$X
   
  klu_temp <- klu_temp[,-(which(colnames(klu_temp) == "X"))]
 
  antallPerKluster <- apply(klu_temp, 2, sum)
  antallPerFil <- apply(klu_temp, 1, sum)
 # summary(antallPerFil)

  #make % add 1 to each sample, and i (number of clusters) to each samplesum so no-one get 0 %, for further analysis 
  klu <- (klu_temp + 1)/t(matrix(rep(antallPerFil + ant_klu_i, ncol(klu_temp)), ncol = length(antallPerFil), byrow = T))
 # summary(apply(klu, 1, sum))
  klu$Pat <- NA
  #find patient from filename 
  if(params$panel == 1){
     for(i in 1:nrow(klu)){
       klu$Pat[i] <- paste("FHI", substr(strsplit(rownames(klu)[i], "FHI")[[1]][2], 1,3))
       if(klu$Pat[i] == "FHI NA"){
          klu$Pat[i] <- paste("Ko", substr(strsplit(rownames(klu)[i], "K1")[[1]][1], 12, 14))
       }
     }
    
     klu$Pat[klu$Pat =="Ko _55"] <- "Ko 550"
     klu$Pat[klu$Pat =="FHI 81_"] <- "FHI 081"
     klu$Pat[klu$Pat =="FHI 95_"] <- "FHI 095"
  } else {
     for(i in 1:nrow(klu)){
       klu$Pat[i] <- paste("FHI", substr(strsplit(rownames(klu)[i], "FHI")[[1]][2], 1,3))
       if(klu$Pat[i] == "FHI NA"){
          klu$Pat[i] <- paste("Ko", substr(strsplit(rownames(klu)[i], "K1")[[1]][2], 1, 3))
       }
       if(klu$Pat[i] == "Ko NA"){
         klu$Pat[i] <- paste("Ko", substr(strsplit(rownames(klu)[i], "_K")[[1]][2], 1, 3))
       }
    
      }
     klu$Pat[klu$Pat =="Ko _55"] <- "Ko 550"
     klu$Pat[klu$Pat =="Ko _50"] <- "Ko 507"
     klu$Pat[klu$Pat =="Ko NA"] <- "Ko 580"
     klu$Pat[klu$Pat =="FHI 81T"] <- "FHI 081"
     klu$Pat[klu$Pat =="FHI 84T"] <- "FHI 084"
     klu$Pat[klu$Pat =="FHI 95_"] <- "FHI 095"
     klu$Pat[grepl("FHI0013", rownames(klu))] <- "FHI 013"
     klu$Pat[grepl("FHI0016", rownames(klu))] <- "FHI 016"
  }
   
   klu$Tid <- "Control"
   for(i in 1:nrow(klu)){
     if(substr(klu$Pat[i],1,3) == "FHI"){
        if(grepl("T2", rownames(klu)[i])){
           klu$Tid[i] <- "T2" 
        } else {
            klu$Tid[i] <- "T1" 
        }
     }
   }

  # table(klu$Tid)
 
 klu$Tid <- factor(klu$Tid, levels = c("Control", "T2",  "T1"))
 
 

 d <- data.frame(klu)
 
 d$Alder <- NA
 d$Sex <- NA
 d$Status <- NA
 
 for(i in 1:nrow(d)){
    if(substr(d$Pat[i],1,1) == "F"){
       radi <- which(meta$Pasientnr == d$Pat[i])
       d$Alder[i] <- meta$Alder[radi]
       d$Sex[i] <- ifelse(meta$Female[radi] == 1, "F", "M")
       d$Status[i] <- "Moderat"
       d$Status[i][grepl("S_", rownames(d)[i])] <- "Severe"
    } else{
       radi <- which(kontrol$kont == substr(d$Pat[i],4,6))
       d$Alder[i] <- kontrol$Alder...2[radi]
       d$Sex[i] <- ifelse(kontrol$Sex[radi] == 1, "F", "M")
       d$Status[i] <- "Control"
    }
 }
 
d$Status <- factor(d$Status, levels = c("Control", "Moderat", "Severe"))
d$Tid <- factor(d$Tid, levels = c("Control",  "T1", "T2"))
d$Sex <- factor(d$Sex, levels = c("F", "M"))
d$StatusTid <- "Control"
d$StatusTid[d$Status == "Moderat" & d$Tid == "T1"] <- "Moderat, T1"
d$StatusTid[d$Status == "Moderat" & d$Tid == "T2"] <- "Moderat, T2"
d$StatusTid[d$Status == "Severe" & d$Tid == "T1"] <- "Severe, T1"
d$StatusTid[d$Status == "Severe" & d$Tid == "T2"] <- "Severe, T2"
d$StatusTid <- factor(d$StatusTid, levels = c("Severe, T1", "Moderat, T1", "Severe, T2", "Moderat, T2","Control" ))
table(d$StatusTid)
d$StatusTidSex <- paste(d$StatusTid, d$Sex)
d$StatusTidSex <- factor(d$StatusTidSex, levels = c( "Severe, T1 M", "Severe, T1 F", "Moderat, T1 M",  "Moderat, T1 F",  "Severe, T2 M",  "Moderat, T2 M", "Moderat, T2 F",  "Control M"  , "Control F"))

d$StatusTidCol <- "green"
d$StatusTidCol[d$StatusTid == "Moderat, T1"] <- "red"
d$StatusTidCol[d$StatusTid == "Severe, T1"] <- "purple"
d$StatusTidCol[d$StatusTid == "Moderat, T2"] <- "yellow"
d$StatusTidCol[d$StatusTid == "Severe, T2"] <- "orange"


d$Tid <- factor(d$Tid, levels = c("Control", "T2", "T1"))

dK <- d[d$Status == "Control",]

dd <- d[!d$Status == "Control",]


med <- dd$Pat[duplicated(dd$Pat)]

dd <- dd[dd$Pat %in% med,]
dd$col <- "red"
dd$col[dd$Status == "Moderat"] <- "blue"

#sorterer i lik rekkefølge
ddT1 <- dd[dd$Tid == "T1",]
ddT2 <- dd[dd$Tid == "T2",]
ddT1 <- ddT1[order(ddT1$Pat),]
ddT2 <- ddT2[order(ddT2$Pat),]

#ddT1$Pat
#ddT2$Pat

return(list(klu = klu, d = d, ddT1 = ddT1, ddT2 = ddT2, dK = dK, dd = dd, antallPerKluster = antallPerKluster))
}
```




```{r,echo = F}
#some functions defined for this dataset. 
pairedPlot <- function(i){ 
  plot( rep(1, nrow(ddT1)), ddT1[,i], xlim = c(0.5,3.5), axes = F,  main = paste("kluster", i, ", antall i kluster = ", antallPerKluster[i]), xlab = "Time", col = ddT1$col, ylim = c(min(min(dK[,i]), min(dd[,i])), c(max(max(dK[,i]), max(dd[,i])))), pch = 16 )
  axis(side = 1, at = c(3, 1,2), labels = c("Control", "T1", "T2"), cex = 2)
  axis(2, cex = 2)
  points( rep(2, nrow(ddT2)), ddT2[,i], col = ddT2$col, pch = 16)
  for(j in 1:nrow(ddT1)){
    lines(c(1,2), c(ddT1[j,i], ddT2[j,i]), col = ddT1$col[j])
  }
  points( rep(3, nrow(dK)), dK[,i], col = "grey", pch = 16)

  points(0.9, mean(ddT1[ddT1$Status == "Moderat",i]), col = "blue", pch = 8, lwd = 2 )
  points(0.9, mean(ddT1[ddT1$Status == "Severe",i]), col = "red", pch = 8, lwd = 2 )
  points(2.1, mean(ddT2[ddT2$Status == "Moderat",i]), col = "blue", pch = 8, lwd = 2 )
  points(2.1, mean(ddT2[ddT2$Status == "Severe",i]), col = "red", pch = 8, lwd = 2 )
  points(3.1, mean(dK[,i]), col = "grey", pch = 8, lwd = 2 )
  
  legend("topright", legend =paste("p =", round(p_mat[i,1],3), "\nadj.p =", round(adj_p[i,1],3)), cex = 2)
}


violinPlot <- function(dat, i){
  x <- dat$Status
  y <- dat[,i]
  group <- dat$StatusTidCol
  Sex <- dat$Sex
  d <- data.frame(x = x, y = y, group = group, Sex = Sex)
  
  g <- ggplot(d, aes(x = x, y = y, group = group, col = Sex)) + 
    geom_violin() + geom_jitter( size = 2, alpha=0.3, position=position_jitter(0.2)) + 
    ggtitle(paste("kluster", i, ", antall i kluster = ", antallPerKluster[i], "p =", round(p_mat[i,1],3), "adj.p =", round(adj_p[i,1],3)))
  g <- g + theme(axis.text = element_text(size = 20), axis.title = element_text(size = 20), title  = element_text(size = 20))
  
  return(g)
}


violinPlotT2Kontroll <- function(dat, i){
  x <- dat$Tid
  y <- dat[,i]
  group <- dat$Tid
  Sex <- dat$Sex
   d <- data.frame(x = x, y = y, group = group, Sex = Sex)
  
  g <- ggplot(d, aes(x = x, y = y, group = group, col = Sex)) + 
    geom_violin() + geom_jitter(size = 2, alpha=0.3, position=position_jitter(0.2)) + 
    ggtitle(paste("kluster", i, ", antall i kluster = ", antallPerKluster[i], "adj.p =", round(adj_p[i,1],3))) + ylab(paste("kluster", i))
  g <- g + theme(axis.text = element_text(size = 20), axis.title = element_text(size = 20), title  = element_text(size = 20))
  
  return(g)
}
```



```{r, echo = F, comment= FALSE, message= FALSE, warning= FALSE, fig.width= 15, fig.height=8}
resExcel <- data.frame(matrix(NA, ncol = 8, nrow =2))
colnames(resExcel) <- c("kluster", "antall", "T1-T2", "T1", "T2", "T2-kontroll", "Regresjon", "Samme som")
resK <- resExcel


for(ant_klu_i in params$muligeK){
  resKForrige <- resK
  resK <- - data.frame(matrix(NA, ncol = 8, nrow =ant_klu_i))
  colnames(resK) <- c("kluster", "antall", "T1-T2", "T1", "T2", "T2-kontroll", "Regresjon", "Samme som")

  print("#######################################################")
  print(paste0("# number of clusters, ", ant_klu_i))
  
  # read data
  dat <- prepare_data()
  klu <- dat$klu
  d <- dat$d
  ddT1 <- dat$ddT1
  ddT2 <- dat$ddT2
  dK <- dat$dK
  dd <- dat$dd
  antallPerKluster <- dat$antallPerKluster
  
  
  print("# wilcoxon test, T1 and T2")
  
  antall_klu <- length(grep("klu", colnames(klu)))
  p_mat <- matrix(NA, nrow = antall_klu, ncol = 1)
  for(i in 1:antall_klu){
    p_mat[i,1] <- wilcox.test(ddT1[,i], ddT2[,i], paired = T)$p.value
  }
  print("summary av p verdier:")
  print(summary(p_mat))
  adj_p <- p_mat
  for(j in 1:ncol(adj_p)){
   adj_p[,j] <- p.adjust(p_mat[,j], method = params$adj_p_methods)
  }
 
  print("summary av adj_p verdier:")
  print(summary(adj_p))
 
  adj_p <- data.frame(adj_p)
 
  mulige <-  which(adj_p < params$adj_p)

  for(i in mulige){
    pairedPlot(i)
    resK[i,"kluster"] <- i
    resK[i,"antall"] <- antallPerKluster[i]
    resK[i, "T1-T2"] <- "X"
  }


  print("# Wilcoxon T1 status")

 
  p_mat <- matrix(NA, nrow = antall_klu, ncol = 1)
  for(i in 1:antall_klu){
     p_mat[i,1] <- wilcox.test(d[d$Tid == "T1",i] ~ d[d$Tid == "T1","Status"])$p.value
  }
  print("summary av p verdier:")
  print(summary(p_mat))
  adj_p <- p_mat
  for(j in 1:ncol(adj_p)){
    adj_p[,j] <- p.adjust(p_mat[,j], method = params$adj_p_methods)
  }
 
  print("summary av adj_p verdier:")
  print(summary(adj_p))
 
  adj_p <- data.frame(adj_p)
  
  mulige <-  which(adj_p < params$adj_p)

  for(i in mulige){
    print(violinPlot(d[d$Tid == "T1",], i))
    resK[i,"kluster"] <- i
    resK[i,"antall"] <- antallPerKluster[i]
    resK[i, "T1"] <- "X"
  }




  print("# Wilcoxon T2 status")

  p_mat <- matrix(NA, nrow = antall_klu, ncol = 1)
  for(i in 1:antall_klu){
     p_mat[i,1] <- wilcox.test(d[d$Tid == "T2",i] ~ d[d$Tid == "T2","Status"])$p.value
  }
  print("summary av p verdier:")
  print(summary(p_mat))
  adj_p <- p_mat
  for(j in 1:ncol(adj_p)){
    adj_p[,j] <- p.adjust(p_mat[,j], method = params$adj_p_methods)
  }
   
  print("summary av adj_p verdier:")
  print(summary(adj_p))
 
  adj_p <- data.frame(adj_p)
 
  mulige <-  which(adj_p < params$adj_p)


  for(i in mulige){
    print(violinPlot(d[d$Tid == "T2",], i))
        resK[i,"kluster"] <- i
    resK[i,"antall"] <- antallPerKluster[i]
    resK[i, "T2"] <- "X"

  }


  print("# Wilcoxon alle T2 mot kontroll")

  p_mat <- matrix(NA, nrow = antall_klu, ncol = 1)
  for(i in 1:antall_klu){
    p_mat[i,1] <- wilcox.test(d[d$Tid %in% c("T2", "Control"),i] ~ d[d$Tid %in% c("T2", "Control"),"Tid"])$p.value
  }
  print("summary av p verdier:")
  print(summary(p_mat))
  adj_p <- p_mat
  for(j in 1:ncol(adj_p)){
    adj_p[,j] <- p.adjust(p_mat[,j], method = params$adj_p_methods)
  }
 
  print("summary av adj_p verdier:")
  print(summary(adj_p))
 
  adj_p <- data.frame(adj_p)
 
  mulige <-  which(adj_p < params$adj_p)
  for(i in mulige){
    print(violinPlotT2Kontroll(d[d$Tid %in% c("T2", "Control"),], i))
    resK[i,"kluster"] <- i
    resK[i,"antall"] <- antallPerKluster[i]
    resK[i, "T2-kontroll"] <- "X"

  }

  print("")
  print("# regression statusTid, sex og alder")
  
  p_mat <- matrix(NA, nrow = antall_klu, ncol = 1)
  colnames(p_mat) <- c("min_p")
 
  for(i in 1:antall_klu){
     p_mat[i,1] <-min(summary(betareg(d[,i] ~ StatusTid + Sex + Alder, data = d ))$coef$mean[2:5,4])
  }
 
  print("summary av p verdier:")

  print(summary(p_mat))
 
  adj_p <- p_mat
  for(j in 1:ncol(adj_p)){
    adj_p[,j] <- p.adjust(p_mat[,j], method = params$adj_p_methods)
  }
 
  print("summary av adj_p verdier:")
  print(summary(adj_p))
 
  adj_p <- data.frame(adj_p)
  mulige <-  which(adj_p$min_p < params$adj_p)
  
 for(i in mulige){
   print(i)
   rm(g)
   res <- summary(betareg(d[,i] ~ StatusTid + Sex + Alder, data = d ))
  # print(res)
   if(res$coefficients$mean["Alder", "Pr(>|z|)" ] < 0.05 ){
     if(res$coefficients$mean["SexM", "Pr(>|z|)" ] < 0.05){
        fit <- betareg(d[,i] ~ StatusTidSex + Alder, data = d )
        res <- summary(fit)
        rsq <- round(res$pseudo.r.squared,2)
        if(any(res$coefficients$mean[2:9, "Pr(>|z|)"] < 0.05)){
           print(paste0("kluster ", i))
           print(res)
           predData <- expand.grid(Alder= min(d$Alder):max(d$Alder), StatusTidSex = levels(d$StatusTidSex))
           for(n in levels(d$StatusTidSex)){
              min_n <- min(d$Alder[d$StatusTidSex == n])
              max_n <- max(d$Alder[d$StatusTidSex == n])
              predData$Alder[predData$StatusTidSex == n & predData$Alder > max_n] <- NA
              predData$Alder[predData$StatusTidSex == n & predData$Alder < min_n] <- NA
           }
           predData <- predData[!is.na(predData$Alder),]

           predData$predict <- predict(fit, newdata = predData) #usikker på hvordan jeg får konfidensintervall. Vent til det skal brukes
           predData$kluster <- predData$predict
            predData$pred_lower <- predict(fit, newdata = predData, type = "quantile", at = nedre)
           predData$pred_upper <- predict(fit, newdata = predData, type = "quantile", at = ovre)
           predData <- data.frame(predData)
           i_alder <- which(colnames(d) == "Alder")
           i_statusTidSex <- which(colnames(d) == "StatusTidSex")
           d2 <- d[,c(i, i_alder, i_statusTidSex)]  
           colnames(d2) <- c("kluster", "Alder", "StatusTidSex")
           g <- ggplot(data = d2, aes(x = Alder, y = kluster, col= StatusTidSex)) +
              geom_point(size = 2) + 
              geom_line(data = predData, aes(x=Alder, y = kluster, col = StatusTidSex), size = 2) + 
             geom_ribbon(data = predData, aes(ymin = pred_lower, ymax = pred_upper, fill = StatusTidSex, color = NULL), alpha = 0.1)
         }
     } else{
        fit <- betareg(d[,i] ~ StatusTid + Alder, data = d )
        res <- summary(fit)
        rsq <- round(res$pseudo.r.squared,2)
        if(any(res$coefficients$mean[2:5, "Pr(>|z|)"] < 0.05)){
           print(paste0("kluster ", i))
           print(res)
           predData <- expand.grid(Alder= min(d$Alder):max(d$Alder), StatusTid = levels(d$StatusTid))
           for(n in levels(d$StatusTid)){
              min_n <- min(d$Alder[d$StatusTid == n])
              max_n <- max(d$Alder[d$StatusTid == n])
              predData$Alder[predData$StatusTid == n & predData$Alder > max_n] <- NA
              predData$Alder[predData$StatusTid == n & predData$Alder < min_n] <- NA
           }

           predData$predict <- predict(fit, newdata = predData) #usikker på hvordan jeg får konfidensintervall. Vent til det skal brukes
           predData$kluster <- predData$predict
            predData$pred_lower <- predict(fit, newdata = predData, type = "quantile", at = nedre)
           predData$pred_upper <- predict(fit, newdata = predData, type = "quantile", at = ovre)
           predData <- data.frame(predData)
           i_alder <- which(colnames(d) == "Alder")
           i_statusTid <- which(colnames(d) == "StatusTid")
           d2 <- d[,c(i, i_alder, i_statusTid)]  
           colnames(d2) <- c("kluster", "Alder", "StatusTid")
           g <- ggplot(data = d2, aes(x = Alder, y = kluster, col= StatusTid)) +
              geom_point(size = 2) + 
              geom_line(data = predData, aes(x=Alder, y = kluster, col = StatusTid), size = 2) +
             geom_ribbon(data = predData, aes(ymin = pred_lower, ymax = pred_upper, fill = StatusTid, color = NULL), alpha = 0.1)
         }
     }
   } else{
     if(res$coefficients$mean["SexM", "Pr(>|z|)" ] < 0.05){
        fit <- betareg(d[,i] ~ StatusTidSex, data = d )
        res <- summary(betareg(d[,i] ~ StatusTidSex, data = d ))
        rsq <- round(res$pseudo.r.squared,2)
        if(any(res$coefficients$mean[2:9, "Pr(>|z|)"] < 0.05)){
           print(paste0("kluster ", i))
           print(res)
           ekte_data <- data.frame(StatusTidSex = d$StatusTidSex, Sex = d$Sex, kluster = d[,i])
           predData <- expand.grid( StatusTidSex = levels(d$StatusTidSex))
           predData$Sex <- "M"
           predData$Sex[grep("F", predData$StatusTidSex)] <- "F"
           predData$kluster <- predict(fit, newdata = predData) #usikker på hvordan jeg får konfidensintervall. Vent til det skal brukes
           predData$pred_lower <- predict(fit, newdata = predData, type = "quantile", at = nedre)
           predData$pred_upper <- predict(fit, newdata = predData, type = "quantile", at = ovre)
           g <- ggplot(ekte_data , aes(x = StatusTidSex, y = kluster, col = Sex)) +
              geom_boxplot(outlier.shape = NA) + 
              geom_jitter(size = 2, alpha=0.3, position=position_jitter(0.2)) +
             geom_errorbar(data = predData, aes(ymin = pred_lower, ymax = pred_upper, col = paste("pred int", params$intervall)), width = 0.2, position = position_dodge(0.9)) + 
             geom_point(data = predData, aes(x = StatusTidSex, y = kluster, col = paste("pred int", params$intervall)), size = 3) 
        }
 
     } else{
         fit <- betareg(d[,i] ~ StatusTid, data = d )
      res <- summary(betareg(d[,i] ~ StatusTid, data = d ))
         rsq <- round(res$pseudo.r.squared,2)
        if(any(res$coefficients$mean[2:5, "Pr(>|z|)"] < 0.05)){
           print(paste0("kluster ", i))
           print(res)
           
      ekte_data <- data.frame(StatusTid = d$StatusTid, Sex = d$Sex, kluster = d[,i])
           predData <- expand.grid( StatusTid = levels(d$StatusTid))
           predData$kluster <- predict(fit, newdata = predData) #usikker på hvordan jeg får konfidensintervall. Vent til det skal brukes
           predData$pred_lower <- predict(fit, newdata = predData, type = "quantile", at = nedre)
           predData$pred_upper <- predict(fit, newdata = predData, type = "quantile", at = ovre)
        
           g <- ggplot(ekte_data , aes(x = StatusTid, y = kluster)) +
              geom_boxplot(outlier.shape = NA) + 
              geom_jitter(aes(col = Sex), size = 2, alpha=0.3, position=position_jitter(0.2)) +
             geom_errorbar(data = predData, aes(ymin = pred_lower, ymax = pred_upper, col = paste("pred int", params$intervall)), width = 0.2, position = position_dodge(0.9)) + 
             geom_point(data = predData, aes(x = StatusTid, y = kluster, col = paste("pred int", params$intervall)), size = 3)
          
          
        }
     } 
   }
   if(exists("g")){
    g <- g + theme(axis.text = element_text(size = 14), axis.title = element_text(size = 20), title  = element_text(size = 20)) + 
    ylab("proportion") 
    g <- g + ggtitle(paste0("kluster ", i, ", pred. intervall = ", params$intervall, ": antall i kluster = ", antallPerKluster[i]))
    print(g)
    d_resid <- data.frame(fitted = fitted(fit), residuals = residuals(fit)) 
    
    g_resid <- ggplot(d_resid, aes(x = fitted, y = residuals)) +
      geom_point() + ggtitle("residual plot") + geom_abline(slope = 0, intercept = 0) + theme(axis.text = element_text(size = 14), axis.title = element_text(size = 20), title  = element_text(size = 20))
    print(g_resid)
    resK[i,"kluster"] <- i
    resK[i,"antall"] <- antallPerKluster[i]
    resK[i,"Regresjon"] <- rsq
   }
 }
  resK <- resK[!is.na(resK$kluster),]
  rownames(resK) <- paste(paste("k", antall_klu, "i", sep = "_"), resK$kluster, sep = "_") 
  
  resK[which(resK$antall %in% resKForrige$antall), "Samme som"] <- "X"
  
  resExcel <- rbind(resExcel, resK)

}

resExcel <- resExcel[-c(1,2),]
write.csv2(resExcel, fs::path(params$utSti, paste0("Result_auto_", params$seed, "_Bon.csv")))


```
