
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


This script was run:

```{r, echo = F}
date()
print(params$seed)
nedre <- ((100 - params$intervall)/2)/100
ovre <- 1 - nedre

```


```{r,include = F, comment= FALSE, message= FALSE}
library(ggplot2)
library(betareg)

analyseSti <- "F:/Forskningsprosjekter/PDB 2794 - Immune responses aga_/Forskningsfiler/JOBO/CyTOF/Analyse i R OUS/"
 meta <- read.csv2(fs::path(analyseSti,"Ous_pasientopplysning_mindre.csv")) #readxl::read_xlsx(fs::path(analyseSti, "STATAfil OUS pasienter FINAL 270121.xlsx"))
 # kontrol <- readxl::read_xlsx(fs::path(analyseSti, "oversikt_kontroller030221.xlsx"))
 # kontrol$Sex <- kontrol$`kjønn (kvinne=1, mann = 2)`
 # kontrol$kont <- kontrol$Løpenummer...1
 # kontrol$alder <- kontrol$Alder...2
 # write.csv2(kontrol[,c("kont", "Sex", "alder")], fs::path(analyseSti, "kontroller_mindre.csv"))
 kontrol <- read.csv2(fs::path(analyseSti, "kontroller_mindre.csv"))
```


```{r, echo = F}
prepare_data <- function(){
  andel_temp <- data.frame(read.csv2(fs::path(params$utSti, paste0(params$fil))))
  rownames(andel_temp) <- andel_temp$X
  andel_temp <- andel_temp[, - 1]
  andel_temp <- andel_temp[,!is.na(andel_temp[1,])]
  antall_surr <- ncol(andel_temp)
  andel <- andel_temp/100
  andel[andel == 0] <- 0.000001

 # summary(apply(andel, 1, sum))
  andel$Pat <- NA
  #find patient from filename 
  if(params$panel == 1){
     for(i in 1:nrow(andel)){
       andel$Pat[i] <- paste("FHI", substr(strsplit(rownames(andel)[i], "FHI")[[1]][2], 1,3))
       if(andel$Pat[i] == "FHI NA"){
          andel$Pat[i] <- paste("Ko", substr(strsplit(rownames(andel)[i], "K1")[[1]][1], 12, 14))
       }
     }
    
     andel$Pat[andel$Pat =="Ko _55"] <- "Ko 550"
     andel$Pat[andel$Pat =="FHI 81_"] <- "FHI 081"
     andel$Pat[andel$Pat =="FHI 95_"] <- "FHI 095"
     andel$Pat[42:48] <- paste0("Ref", 1:7)
  } else {
     for(i in 1:nrow(andel)){
       andel$Pat[i] <- paste("FHI", substr(strsplit(rownames(andel)[i], "FHI")[[1]][2], 1,3))
       if(andel$Pat[i] == "FHI NA"){
          andel$Pat[i] <- paste("Ko", substr(strsplit(rownames(andel)[i], "K1")[[1]][2], 1, 3))
       }
       if(andel$Pat[i] == "Ko NA"){
         andel$Pat[i] <- paste("Ko", substr(strsplit(rownames(andel)[i], "_K")[[1]][2], 1, 3))
       }
    
      }
      andel$Pat[44:50] <- paste0("Ref", 1:7)
     andel$Pat[andel$Pat =="Ko _55"] <- "Ko 550"
     andel$Pat[andel$Pat =="Ko _50"] <- "Ko 507"
     andel$Pat[andel$Pat =="Ko NA"] <- "Ko 580"
     andel$Pat[andel$Pat =="FHI 81T"] <- "FHI 081"
     andel$Pat[andel$Pat =="FHI 84T"] <- "FHI 084"
     andel$Pat[andel$Pat =="FHI 95_"] <- "FHI 095"
     andel$Pat[grepl("FHI0013", rownames(andel))] <- "FHI 013"
     andel$Pat[grepl("FHI0016", rownames(andel))] <- "FHI 016"
  }
   
   andel$Tid <- "Control"
   for(i in 1:nrow(andel)){
     if(substr(andel$Pat[i],1,3) == "FHI"){
        if(grepl("T2", rownames(andel)[i])){
           andel$Tid[i] <- "T2" 
        } else {
            andel$Tid[i] <- "T1" 
        }
     }
   }
   andel$Tid[substr(andel$Pat,1, 1) == "R"] <- "Ref"

  # table(andel$Tid)
 
 andel$Tid <- factor(andel$Tid, levels = c("Control", "T2",  "T1", "Ref"))
 
 

 d <- data.frame(andel)
 
 d$Alder <- NA
 d$Sex <- NA
 d$Status <- NA
 
 for(i in 1:nrow(d)){
    if(substr(d$Pat[i],1,1) == "F"){
            radi <- which(meta$Pasientnr == d$Pat[i])
       d$Alder[i] <- meta$Alder[radi]
       d$Sex[i] <- ifelse(meta$Female[radi] == 1, "F", "M")
       d$Status[i] <- "Moderat"
       d$Status[i][grepl("S_", rownames(d)[i])] <- "Severe"
    } else{
      if(substr(d$Pat[i],1, 1) == "K"){
       radi <- which(kontrol$kont == substr(d$Pat[i],4,6))
       d$Alder[i] <- kontrol$alder[radi] #as.numeric(kontrol[radi, grep("Alder", colnames(kontrol))[1]])
       d$Sex[i] <- ifelse(kontrol$Sex[radi] == 1, "F", "M") #ifelse(kontrol$`kjønn (kvinne=1, mann = 2)`[radi] == 1, "F", "M")
       d$Status[i] <- "Control"
      }
    }
 }
 
d$Status <- factor(d$Status, levels = c("Control", "Moderat", "Severe"))
d$Tid <- factor(d$Tid, levels = c("Control",  "T1", "T2"))
d$Sex <- factor(d$Sex, levels = c("F", "M"))
d$StatusTid <- "Control"
d$StatusTid[d$Status == "Moderat" & d$Tid %in% "T1"] <- "Moderat, T1"
d$StatusTid[d$Status == "Moderat" & d$Tid %in% "T2"] <- "Moderat, T2"
d$StatusTid[d$Status == "Severe" & d$Tid %in% "T1"] <- "Severe, T1"
d$StatusTid[d$Status == "Severe" & d$Tid %in% "T2"] <- "Severe, T2"
d$StatusTid <- factor(d$StatusTid, levels = c("Severe, T1", "Moderat, T1", "Severe, T2", "Moderat, T2","Control" ))
table(d$StatusTid)
d$StatusTidSex <- paste(d$StatusTid, d$Sex)
d$StatusTidSex <- factor(d$StatusTidSex, levels = c( "Severe, T1 M", "Severe, T1 F", "Moderat, T1 M",  "Moderat, T1 F",  "Severe, T2 M",  "Moderat, T2 M", "Moderat, T2 F",  "Control M"  , "Control F"))

d$StatusTidSexF <- as.character(d$StatusTidSex)
d$StatusTidSexF <- factor(d$StatusTidSexF, levels = c(  "Severe, T1 F", "Severe, T1 M", "Moderat, T1 F", "Moderat, T1 M",    "Severe, T2 M",  "Moderat, T2 F",  "Moderat, T2 M" , "Control F", "Control M" ))


d$StatusTidCol <- "green"
d$StatusTidCol[d$StatusTid %in% "Moderat, T1"] <- "red"
d$StatusTidCol[d$StatusTid %in% "Severe, T1"] <- "purple"
d$StatusTidCol[d$StatusTid %in% "Moderat, T2"] <- "yellow"
d$StatusTidCol[d$StatusTid %in% "Severe, T2"] <- "orange"


d$Tid <- factor(d$Tid, levels = c("Control", "T2", "T1"))

dK <- d[d$Status %in% "Control",]

dd <- d[!d$Status %in% "Control",]


med <- dd$Pat[duplicated(dd$Pat)]

dd <- dd[dd$Pat %in% med,]
dd$col <- "red"
dd$col[dd$Status %in% "Moderat"] <- "blue"

#sorterer i lik rekkefølge
ddT1 <- dd[dd$Tid %in% "T1",]
ddT2 <- dd[dd$Tid %in% "T2",]
ddT1 <- ddT1[order(ddT1$Pat),]
ddT2 <- ddT2[order(ddT2$Pat),]

#ddT1$Pat
#ddT2$Pat

return(list(andel = andel, d = d, ddT1 = ddT1, ddT2 = ddT2, dK = dK, dd = dd, antall_surr = antall_surr))
}
```







```{r, echo = F, comment= FALSE, message= FALSE, warning= FALSE, fig.width= 15, fig.height=8}

  dat <- prepare_data()
  andel <- dat$andel
  d <- dat$d
  ddT1 <- dat$ddT1
  ddT2 <- dat$ddT2
  dK <- dat$dK
  dd <- dat$dd
  antall_surr <- dat$antall_surr
 # antallPerandelster <- dat$antallPerandelster
 

  


 # print("")
#  print("# regression statusTid, sex og alder")
  
 
 
  d2 <- d
  d <- d[!substr(d$Pat,1,1) == "R",]
  g <- NA

  mulige <- 1:(grep("Pat", colnames(d))-1)
 for(i in mulige){
   if(exists("g")){
     rm(g)
   }
   print("###")
   print("###")
   
   print(colnames(d)[i])
   
   print(summary(d[,i]))
   if(sort(d[,i], decreasing = T)[5] < 0.0005){
     print("almost all equal to 0, 5 largest values:")
     print(sort(d[,i], decreasing = T)[1:5])
   } else {
   if(max(d[,i]) > 0.001){
   d$y <- d[,i] + min(d[d[,i] > 0,i])/100
   res <- summary(betareg(y ~ StatusTid + Sex + Alder, data = d ))
  # print(res)
   if(res$coefficients$mean["Alder", "Pr(>|z|)" ] < 0.05 ){
     if(res$coefficients$mean["SexM", "Pr(>|z|)" ] < 0.05){
        fit <- betareg(y ~ StatusTidSex + Alder, data = d )
        res <- summary(fit)
        fitF <- betareg(y ~ StatusTidSexF + Alder, data = d )
        resF <- summary(fitF)
        if(any(res$coefficients$mean[2:9, "Pr(>|z|)"] < 0.05)|any(resF$coefficients$mean[2:9, "Pr(>|z|)"] < 0.05)){
           print(paste0(colnames(d)[i]))
           print(res)
           print(resF)
           predData <- expand.grid(Alder= min(d$Alder):max(d$Alder), StatusTidSex = levels(d$StatusTidSex))
           for(n in levels(d$StatusTidSex)){
              min_n <- min(d$Alder[d$StatusTidSex == n])
              max_n <- max(d$Alder[d$StatusTidSex == n])
              predData$Alder[predData$StatusTidSex == n & predData$Alder > max_n] <- NA
              predData$Alder[predData$StatusTidSex == n & predData$Alder < min_n] <- NA
           }
           predData <- predData[!is.na(predData$Alder),]

           predData$predict <- predict(fit, newdata = predData)
            predData$pred_lower <- predict(fit, newdata = predData, type = "quantile", at = nedre)
           predData$pred_upper <- predict(fit, newdata = predData, type = "quantile", at = ovre)
           predData$navn <- predData$predict
           predData <- data.frame(predData)
           i_alder <- which(colnames(d) == "Alder")
           i_statusTidSex <- which(colnames(d) == "StatusTidSex")
           d2 <- d[,c(i, i_alder, i_statusTidSex)]  
           colnames(d2) <- c("navn", "Alder", "StatusTidSex")
           g <- ggplot(data = d2, aes(x = Alder, y = navn, col= StatusTidSex)) +
              geom_point(size = 2) + 
              geom_line(data = predData, aes(x=Alder, y = navn, col = StatusTidSex), size = 2) + 
             geom_ribbon(data = predData, aes(ymin = pred_lower, ymax = pred_upper, fill = StatusTidSex, color = NULL), alpha = 0.1)
         }
     } else{
        fit <- betareg(y ~ StatusTid + Alder, data = d )
        res <- summary(fit)
        if(any(res$coefficients$mean[2:5, "Pr(>|z|)"] < 0.05)){
                print(paste0( colnames(d)[i]))
     
         #  print(paste0("andelster ", i))
           print(res)
           predData <- expand.grid(Alder= min(d$Alder):max(d$Alder), StatusTid = levels(d$StatusTid))
           for(n in levels(d$StatusTid)){
              min_n <- min(d$Alder[d$StatusTid == n])
              max_n <- max(d$Alder[d$StatusTid == n])
              predData$Alder[predData$StatusTid == n & predData$Alder > max_n] <- NA
              predData$Alder[predData$StatusTid == n & predData$Alder < min_n] <- NA
           }

           predData$predict <- predict(fit, newdata = predData) #usikker på hvordan jeg får konfidensintervall. Vent til det skal brukes
           predData$navn <- predData$predict
            predData$pred_lower <- predict(fit, newdata = predData, type = "quantile", at = nedre)
           predData$pred_upper <- predict(fit, newdata = predData, type = "quantile", at = ovre)
           predData <- data.frame(predData)
           i_alder <- which(colnames(d) == "Alder")
           i_statusTid <- which(colnames(d) == "StatusTid")
           d2 <- d[,c(i, i_alder, i_statusTid)]  
           colnames(d2) <- c("navn", "Alder", "StatusTid")
           g <- ggplot(data = d2, aes(x = Alder, y = navn, col= StatusTid)) +
              geom_point(size = 2) + 
              geom_line(data = predData, aes(x=Alder, y = navn, col = StatusTid), size = 2) +
             geom_ribbon(data = predData, aes(ymin = pred_lower, ymax = pred_upper, fill = StatusTid, color = NULL), alpha = 0.1)
         }
     }
   } else{
     if(res$coefficients$mean["SexM", "Pr(>|z|)" ] < 0.05){
        fit <- betareg(d[,i] ~ StatusTidSex, data = d )
        res <- summary(betareg(y ~ StatusTidSex, data = d ))
        resF <- summary(betareg(y ~ StatusTidSexF, data = d ))

        if(any(res$coefficients$mean[2:9, "Pr(>|z|)"] < 0.05) | any(resF$coefficients$mean[2:9, "Pr(>|z|)"] < 0.05)){
     #      print(paste0("andelster ", i))
            print(paste0( colnames(d)[i]))
          print(res)
           print(resF)
           ekte_data <- data.frame(StatusTidSex = d$StatusTidSex, Sex = d$Sex, kluster = d[,i])
           predData <- expand.grid( StatusTidSex = levels(d$StatusTidSex))
           predData$Sex <- "M"
           predData$Sex[grep("F", predData$StatusTidSex)] <- "F"
           predData$kluster <- predict(fit, newdata = predData) #usikker på hvordan jeg får konfidensintervall. Vent til det skal brukes
           predData$pred_lower <- predict(fit, newdata = predData, type = "quantile", at = nedre)
           predData$pred_upper <- predict(fit, newdata = predData, type = "quantile", at = ovre)
           
           g <- ggplot(ekte_data , aes(x = StatusTidSex, y = kluster, col = Sex)) +
              geom_boxplot(outlier.shape = NA) + 
              geom_jitter(size = 2, alpha=0.3, position=position_jitter(0.2)) +
             geom_errorbar(data = predData, aes(ymin = pred_lower, ymax = pred_upper, col = paste("pred int", params$intervall)), width = 0.2, position = position_dodge(0.9)) + 
             geom_point(data = predData, aes(x = StatusTidSex, y = kluster, col = paste("pred int", params$intervall)), size = 3) 
           
        }
 
     } else{
         fit <- betareg(d[,i] ~ StatusTid, data = d )
      res <- summary(betareg(y ~ StatusTid, data = d ))
        if(any(res$coefficients$mean[2:5, "Pr(>|z|)"] < 0.05)){
     #      print(paste0("andelster ", i))
          print(paste0( colnames(d)[i]))
            print(res)
           
          ekte_data <- data.frame(StatusTid = d$StatusTid, Sex = d$Sex, kluster = d[,i])
           predData <- expand.grid( StatusTid = levels(d$StatusTid))
           predData$kluster <- predict(fit, newdata = predData) #usikker på hvordan jeg får konfidensintervall. Vent til det skal brukes
           predData$pred_lower <- predict(fit, newdata = predData, type = "quantile", at = nedre)
           predData$pred_upper <- predict(fit, newdata = predData, type = "quantile", at = ovre)
        
           g <- ggplot(ekte_data , aes(x = StatusTid, y = kluster)) +
              geom_boxplot(outlier.shape = NA) + 
              geom_jitter(aes(col = Sex), size = 2, alpha=0.3, position=position_jitter(0.2)) +
             geom_errorbar(data = predData, aes(ymin = pred_lower, ymax = pred_upper, col = paste("pred int", params$intervall)), width = 0.2, position = position_dodge(0.9)) + 
             geom_point(data = predData, aes(x = StatusTid, y = kluster, col = paste("pred int", params$intervall)), size = 3)
          
          
        }
     } 
   
   }
   if(exists("g")){
     print("########")
    print(colnames(d)[i])
 
    g <- g + theme(axis.text = element_text(size = 14), axis.title = element_text(size = 20), title  = element_text(size = 20)) + 
    ylab("proportion") 
    g <- g + ggtitle(paste0(colnames(d)[i], ", pred. intervall = ", params$intervall#, ": antall i andelster = ", antallPerandelster[i]
    ))
    print(g)
    d_resid <- data.frame(fitted = fitted(fit), residuals = residuals(fit)) 
    
    g_resid <- ggplot(d_resid, aes(x = fitted, y = residuals)) +
      geom_point() + ggtitle("residual plot") + geom_abline(slope = 0, intercept = 0) + theme(axis.text = element_text(size = 14), axis.title = element_text(size = 20), title  = element_text(size = 20))
    print(g_resid)
   
   }
   }
 }
}

```
